spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
  config:
    import:
      - optional:file:.env[.properties]

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXP}
server:
  servlet:
    encoding:
      charset: UTF-8

logging:
  level:
    root: info
  file:
    name: server.log
